[project]
name = "queai-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "langchain[google-genai]>=0.3.26",
    "langgraph>=0.5.3",
]
